### PR TITLE
feat(pvc): add support for creating PVC via chart

### PR DESCRIPTION
**Pull request by PixelJonas**
This PR adds support for PVCs to be created via the chart

PVC created via the `persistence` key are also auto-mounted to every deployment

### CODE REVIEW

**Comment by bo0tzz** [comment]
Are these just copy pasted from the library chart (or do they need reviewing)?

**Comment by PixelJonas** [comment]
mostly just copy&paste

**Comment by onichandame** [comment]
sorry to revive the closed issue. what is the current state of 'auto creating pvc via chart'? is it not intended or on the roadmap?

**Comment by bo0tzz** [comment]
I decided against it. It was significantly easier to take the current approach, and in my personal opinion important volumes are best managed directly anyways.

**Pull request closed without merging**
