### PR TITLE
Update App Version to 1.79.1

### PR DESCRIPTION
**Pull request by hofq**
Update Chart Version, as the last commit has not created an Release

### CODE REVIEW

**Comment by hofq** [comment]
Runs stable, without any new Bugs in Android and Web App
grafik

**Comment by PixelJonas** [comment]
LGTM

**Review by PixelJonas — APPROVED** [review]

**Comment by bo0tzz** [comment]
Fwiw: We shouldn't need to do chart releases just to update the app version, as people can override it in their own values.yaml

**Comment by PixelJonas** [comment]
yeah, I thought about moving the image tag to `release`. This would mean that we should be fast for adapting to breaking changes.

Do you agree @bo0tzz ?

**Comment by bo0tzz** [comment]
No, I disagree. There is no real need to keep the default image tag in the chart up to date (although we should still bump it if we're doing a release for other reasons), and I'm also not a fan in general of mutable/moving tags like `release` ;)

**Comment by hofq** [comment]
Would be nice if there are regular updates to the Chart because users then know that the Chart works with the specified image.

Also as the Chart is official, synced release Versions keep it simple to rollback or trace back any issues.


Also this would remove the need for external tools like argo image updater to keep the Image up to date

**Comment by PixelJonas** [comment]
I see your point @hofq  but without having something like a CI/CD pipeline to test the chart against the latest Immich release this might introduce another set of challenges. Testing new versions can be easily done by anyone by changing the `image.tag`

**Pull request merged**
