### PR TITLE
WIP: helm releaser - gh-pages

### PR DESCRIPTION
**Pull request by orbatschow**
NOTE: This PR refers to the main branch at the moment. The `gh-pages` branch does not exist and needs to be created beforehand. After creating the new branch it is necessary to merge the changes into the newly created `gh-pages` branch

This will provide a README.md for the helm repository branch.
It is also necessary in order to make the helm-releaser PR work.

Related: https://github.com/immich-app/immich-charts/pull/17

### CODE REVIEW

**Comment by PixelJonas** [comment]
@orbatschow can you resolve the conflict? looks like a some changes of this branch conflict with your other PR

**Comment by PixelJonas** [comment]
I also added the gh-pages branch
https://github.com/immich-app/immich-charts/tree/gh-pages

**Comment by orbatschow** [comment]
@PixelJonas I updated my branch and there shouldn't be any more conflicts.

**Comment by orbatschow** [comment]
@PixelJonas Note: after merging this PR, the Helm repository will only start working, when there is a new commit on the main branch, that will bump the chart version. If you would like I can open a PR for this.

**Pull request merged**
