### PR TITLE
Changes probes url its now with /api/

### PR DESCRIPTION
**Pull request by yodatak**
Like in the demo server probe must change because  https://demo.immich.app/api/server-info/ping works but not  https://demo.immich.app/server-info/ping

### CODE REVIEW

**Comment by yodatak** [comment]
And why not document more default yaml value for encoding with nvidia/AMD/Intel

**Comment by yodatak** [comment]
@bo0tzz  
@btajuddin
For review ^

**Comment by yodatak** [comment]
hum not sure with but now the container restart because it can't have the probe  :/

**Review by jrasm91 — APPROVED** [review]

**Comment by bo0tzz** [comment]
Superseded by #75

**Pull request closed without merging**
