### PR TITLE
WIP: helm releaser - Github Action

### PR DESCRIPTION
**Pull request by orbatschow**
This PR will tackle the following issues:

- https://github.com/immich-app/immich-charts/issues/14 (partially)
- https://github.com/immich-app/immich-charts/issues/12
- https://github.com/immich-app/immich-charts/issues/13

It will introduce a Github action, that will run, when a push is done on the main branch.
The helm-releaser action will publish a helm chart with the current Chart version.
The repository was restructured a little bit to conform to the official guidelines/requirements:

```
The sources of all the charts can be placed under the main branch. The charts should be placed under /charts directory at the top-level of the directory tree.
```

rel: https://helm.sh/docs/howto/chart_releaser_action/

In order to for the pushes to be successful a `gh-pages` must be created.
This PR: https://github.com/immich-app/immich-charts/pull/16 will hold the necessary changes for this branch and has to be merged before completing this PR.

After both PR's are merged, the helm repository can be tested by following this instructions:

https://github.com/orbatschow/immich-charts/tree/gh-pages

### CODE REVIEW

**Comment by bo0tzz** [comment]
This is great, thank you! You mention this PR also covers #15, but I don't see that in the diff. Is that still WIP?

**Comment by orbatschow** [comment]
Ouch, I meant to say, that it will partially solve https://github.com/immich-app/immich-charts/issues/14 - sorry!

I updated the description

**Comment by PixelJonas** [comment]
this looks awesome. Let me review it on sunday and then LTM

**Comment by PixelJonas** [comment]
looking at the changes (other than changing the directory) I see no reason not to merge it

**Comment by bo0tzz** [comment]
Thank you!

**Pull request merged**
